### ISSUE TITLE
Geeetech A10M filament change no work well E1 E2 problem

### ISSUE THREAD

**Issue by kondorzs** [Vertabreak/Marlin#351]
Hi I upgraded my A10M printer new firmware but I think Filament change and load and unload no work good. I Like chage E0 (E1) put work. Like change (Load E1..(E2) put and load E1 filament again. And I repet metod and load E2. So If put E1menu--> load load E1 and Put E2 menu --> load E1 and put E1menu  again and load E1 .

**Comment by Vertabreak** [comment]
this is user error due to lack of understanding of vtools furthermore the config only maintained on this repo bugs must be filed with marlin.

**Comment by kondorzs** [comment]
So My problem no problem? Work good If just one extruder work If put menu E1 and E2?

**Comment by Vertabreak** [comment]
you must activate the correct Vtool before selecting filament change failing to do so will only do E0. 
once the Vtool for 0%/100% is active rather then 100%/0% filament change works. 
again this is user error due to lack of understanding suggest reading the marlin wiki and fully understanding how vtools work.
